export const metadata={id:'energy',title:'Arena Cósmica',description:'Domine o voo, o combate e sua energia em três duelos até o eclipse final.',controls:[{action:'jump',label:'Voo / pousar'},{action:'attack',label:'Combo'},{action:'special',label:'Segurar / soltar raio'},{action:'dash',label:'Esquiva'},{action:'guard',label:'Defender / baixo: carregar'},{action:'interact',label:'Transformar / continuar'}]};
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rivals=[{name:'Iara • Treino nas nuvens',hp:180,color:'#eaaf76',speed:85},{name:'Vetor • Torneio orbital',hp:300,color:'#b49aee',speed:115},{name:'Regente do Eclipse',hp:480,color:'#eb809f',speed:125}];
export function createGame(runtime){
 let stored;try{stored=runtime.save.load()||{};}catch{stored={};}const n=(v,d,a,b)=>Number.isFinite(v)?clamp(Math.floor(v),a,b):d;
 let stage=n(stored.stage,0,0,2),mastery=n(stored.mastery,0,0,9999),wins=n(stored.wins,0,0,999),p,e,time=0,combo=0,comboWindow=0,attack=0,charge=0,beam=0,beamY=0,beamDir=1,fx=[],shots=[],state='fight',transition=0,report=0,message='',messageTime=0,score=0;
 const save=()=>runtime.save.store({version:1,stage,mastery,wins,completed:state==='won'});
 const say=t=>{message=t;messageTime=4;runtime.message?.(t);};
 const sound=(name,f)=>{try{runtime.audio?.play(name,{frequency:f,duration:.12,volume:.12});}catch{}};
 function start(){p={x:230,y:425,hp:150,energy:100,face:1,flying:false,inv:0,dash:0,dashCd:0,transformed:false,transformTime:0};e={x:720,y:425,hp:rivals[stage].hp,maxHp:rivals[stage].hp,face:-1,mode:'approach',timer:1.2,phase:1,hit:0,targetY:425,attackKind:'strike'};shots=[];fx=[];charge=0;beam=0;combo=0;attack=0;comboWindow=0;state='fight';transition=0;report=0;say(stage===0?'Treino: combo de perto; segure Raio e solte. Escudo + baixo carrega energia.':stage===1?'Torneio: voe para escapar dos disparos. Domínio 6 libera a transformação!':'Final: observe os avisos. O Regente muda de padrão com metade da vida.');}
 function burst(x,y,color,count=12){for(let i=0;i<count;i++){const a=i/count*TAU;fx.push({x,y,vx:Math.cos(a)*(70+Math.random()*90),vy:Math.sin(a)*(70+Math.random()*90),life:.5,color});}}
 function hitEnemy(damage,knock=0){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-damage);e.hit=.2;e.x=clamp(e.x+p.face*knock,50,910);mastery++;score+=Math.round(damage);burst(e.x,e.y-23,'#b8efff');sound('attack',420);if(!e.hp){state='between';transition=1;wins++;save();say(stage===2?'O eclipse se desfez. Você protegeu as ilhas celestes!':'Duelo vencido! Interaja para seguir ao próximo desafio.');if(stage===2){state='won';save();runtime.complete({score:score+mastery*20,stars:3});}}}
 function hurt(amount){if(p.inv>0||state!=='fight')return;if(runtime.input.down('guard')&&p.energy>=12){p.energy-=12;amount*=.18;burst(p.x,p.y-20,'#91e5fd');}else{p.inv=.65;burst(p.x,p.y-20,'#f5c3a2');}p.hp=Math.max(0,p.hp-amount);if(!p.hp){state='down';say('Respire e tente de novo. Interaja para repetir este duelo.');}}
 function update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(.05,dt);time+=dt;messageTime-=dt;transition-=dt;beam=Math.max(0,beam-dt);fx.forEach(f=>{f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;});fx=fx.filter(f=>f.life>0);report-=dt;
  if(report<=0){report=.25;runtime.report({title:'Arena Cósmica',message:rivals[stage].name,score,level:stage+1,health:Math.ceil(p.hp),energy:Math.floor(p.energy),coins:mastery,status:state==='fight'?'Em combate':state==='won'?'Vitória':'Interaja para continuar'});}
  if(state!=='fight'){if(runtime.input.pressed('interact')&&transition<=0&&state!=='won'){if(state==='between'){stage++;save();}start();}return;}
  p.inv=Math.max(0,p.inv-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.dash=Math.max(0,p.dash-dt);attack=Math.max(0,attack-dt);comboWindow-=dt;e.hit=Math.max(0,e.hit-dt);
  const ax=runtime.input.axis('x'),ay=runtime.input.axis('y'),guard=runtime.input.down('guard'),charging=guard&&runtime.input.down('down');
  if(runtime.input.pressed('jump'))p.flying=!p.flying;
  if(ax&&!guard)p.face=Math.sign(ax);
  if(runtime.input.pressed('dash')&&p.energy>=18&&p.dashCd<=0){p.energy-=18;p.dash=.18;p.dashCd=.7;p.inv=.25;burst(p.x,p.y-20,'#a4dbff');}
  if(p.dash>0)p.x+=p.face*650*dt;else if(!charging){p.x+=ax*(guard?75:235)*dt;if(p.flying)p.y+=ay*210*dt;}
  if(!p.flying)p.y=Math.min(425,p.y+260*dt);p.x=clamp(p.x,40,920);p.y=clamp(p.y,115,425);
  p.energy=clamp(p.energy+dt*(charging?32:charge>0?0:p.transformed?-8:7),0,100);if(p.transformed){p.transformTime-=dt;if(p.energy<=0||p.transformTime<=0)p.transformed=false;}
  if(runtime.input.pressed('interact')){if(mastery>=6&&p.energy>=60&&!p.transformed){p.transformed=true;p.transformTime=18;p.energy-=30;say('Forma Aurora! Força ampliada por 18 segundos.');burst(p.x,p.y-20,'#ffe2a1',24);}else if(!p.transformed)say('Forma Aurora: exige domínio 6 e 60 de energia. Acerte golpes para dominar.');}
  if(runtime.input.pressed('attack')&&attack<=0&&p.energy>=7&&!guard){p.energy-=7;combo=comboWindow>0?combo%3+1:1;comboWindow=.85;attack=.23;if(Math.abs(e.x-p.x)<100&&Math.abs(e.y-p.y)<65&&(e.x-p.x)*p.face>-15)hitEnemy((combo===3?26:16)*(p.transformed?1.65:1),combo===3?65:12);sound('attack',300+combo*60);}
  if(runtime.input.down('special')&&!guard&&p.energy>10)charge=Math.min(1.6,charge+dt);
  if((runtime.input.released('special')||!runtime.input.down('special'))&&charge>0){const power=Math.min(charge,p.energy/30);p.energy=Math.max(0,p.energy-(12+power*24));beam=.28;beamY=p.y-24;beamDir=p.face;if((e.x-p.x)*p.face>0&&Math.abs(e.y-p.y)<26+power*22)hitEnemy((18+power*37)*(p.transformed?1.4:1),25);charge=0;sound('beam',160);}
  if(state!=='fight')return;
  e.phase=stage===2&&e.hp<e.maxHp*.5?2:1;e.face=p.x>e.x?1:-1;e.timer-=dt;
  if(e.mode==='windup'){if(e.timer<=0){e.mode='recover';e.timer=e.phase===2?.65:1;if(e.attackKind==='strike'){if(Math.abs(e.x-p.x)<130&&Math.abs(e.y-p.y)<75)hurt(18+stage*5);burst(e.x+e.face*70,e.y-20,'#ffb69b',16);}else{for(let i=0;i<(e.phase===2?3:1);i++)shots.push({x:e.x,y:e.targetY-24+(i-1)*(e.phase===2?56:0),vx:e.face*(260+stage*45),life:4});}}}
  else if(e.mode==='recover'){if(e.timer<=0){e.mode='approach';e.timer=.65;}}
  else{const d=Math.abs(p.x-e.x);e.x+=e.face*rivals[stage].speed*dt*(d>78?1:0);e.y+=clamp(p.y-e.y,-1,1)*(stage?90:45)*dt;e.x=clamp(e.x,45,915);e.y=clamp(e.y,115,425);if(e.timer<=0){e.mode='windup';e.attackKind=d<135?'strike':'blast';e.targetY=p.y;e.timer=stage===0?1.1:e.phase===2?.68:.9;}}
  for(const s of shots){s.x+=s.vx*dt;s.life-=dt;if(Math.abs(s.x-p.x)<24&&Math.abs(s.y-(p.y-24))<29){hurt(20+stage*4);s.life=0;}}shots=shots.filter(s=>s.life>0&&s.x>-30&&s.x<990);
 }
 function text(c,t,x,y,size=16,color='#f1f5ff',align='left'){c.fillStyle=color;c.textAlign=align;c.font=`600 ${size}px system-ui`;c.fillText(t,x,y);}
 function bar(c,x,y,w,v,color){c.fillStyle='#152740';c.fillRect(x,y,w,8);c.fillStyle=color;c.fillRect(x,y,w*clamp(v,0,1),8);}
 function fighter(c,o,color,hero=false){c.save();c.translate(o.x,o.y);c.fillStyle='rgba(9,18,46,.2)';c.beginPath();c.ellipse(0,425-o.y+9,24,7,0,0,TAU);c.fill();if(hero&&(p.transformed||charge>0||runtime.input.down('guard'))){c.strokeStyle=p.transformed?'#ffdc8e':'#9ee8fa';c.lineWidth=3;c.beginPath();c.ellipse(0,-25,30+charge*14,44+Math.sin(time*4)*3,0,0,TAU);c.stroke();}c.scale(o.face,1);const bob=runtime.settings?.reducedMotion?0:Math.sin(time*6)*2;c.translate(0,bob);c.fillStyle='#202947';c.fillRect(-14,-10,10,21);c.fillRect(4,-10,10,21);c.fillStyle=color;c.beginPath();c.moveTo(-19,-40);c.lineTo(15,-40);c.lineTo(19,-8);c.lineTo(-17,-8);c.fill();c.fillStyle='#ecdbc5';c.beginPath();c.arc(0,-51,12,0,TAU);c.fill();c.fillStyle=hero?(p.transformed?'#fce69b':'#38557b'):'#40385c';c.beginPath();c.moveTo(-13,-54);c.lineTo(-15,-69);c.lineTo(-4,-63);c.lineTo(3,-76);c.lineTo(9,-63);c.lineTo(17,-66);c.lineTo(12,-50);c.fill();c.fillStyle='#122840';c.fillRect(5,-53,4,3);c.fillStyle='#f5c6a7';c.fillRect(12,-35,hero&&attack>0?42:16,9);c.fillStyle='#fff2bc';c.fillRect(-17,-15,35,5);c.restore();}
 function draw(c){c.save();const g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,['#233958','#352955','#201d3c'][stage]);g.addColorStop(1,'#7998ad');c.fillStyle=g;c.fillRect(0,0,960,540);c.fillStyle=stage===2?'#e2b2cc':'#e9dcbc';c.beginPath();c.arc(745,135,stage===2?57:40,0,TAU);c.fill();if(stage===2){c.fillStyle='#292441';c.beginPath();c.arc(763,122,53,0,TAU);c.fill();}
  for(let i=0;i<6;i++){const x=i*205-70+(runtime.settings?.reducedMotion?0:Math.sin(time*.1+i)*9);c.fillStyle=i%2?'#506784':'#596d8d';c.beginPath();c.moveTo(x,365);c.lineTo(x+65,175+(i%3)*40);c.lineTo(x+155,365);c.fill();c.fillStyle='#bcc7d0';c.beginPath();c.moveTo(x+65,175+(i%3)*40);c.lineTo(x+43,240+(i%3)*28);c.lineTo(x+85,225+(i%3)*30);c.fill();}
  for(let i=0;i<5;i++){c.fillStyle='rgba(213,229,240,.16)';c.beginPath();c.ellipse(i*240+Math.sin(time*.08+i)*20,300+i%2*35,140,19,0,0,TAU);c.fill();}c.fillStyle='#344866';c.fillRect(0,433,960,107);c.fillStyle='#aeb8c1';c.fillRect(20,428,920,12);c.fillStyle='#798d9c';c.fillRect(35,440,890,24);c.strokeStyle='#b3c3cb';c.lineWidth=2;for(let x=40;x<950;x+=80){c.beginPath();c.moveTo(x,441);c.lineTo(x-45,540);c.stroke();}for(let i=0;i<4;i++){c.fillStyle='#64798c';c.fillRect(i*285+35,355,18,74);c.fillStyle='#d1d5c6';c.fillRect(i*285+28,349,32,12);}
  if(e.mode==='windup'&&state==='fight'){c.fillStyle='rgba(255,183,133,.22)';c.strokeStyle='#ffc396';c.lineWidth=2;if(e.attackKind==='blast'){c.fillRect(0,e.targetY-47,960,46);c.strokeRect(0,e.targetY-47,960,46);text(c,'RAIO → MUDE DE ALTURA',480,e.targetY-56,13,'#ffe0ae','center');}else{c.beginPath();c.arc(e.x,e.y-20,118,0,TAU);c.fill();c.stroke();}text(c,'!',e.x,e.y-95,27,'#ffe0ae','center');}
  if(e.hp>0)fighter(c,e,e.hit>0?'#e4d7e8':rivals[stage].color);c.globalAlpha=p.inv>0?.65:1;fighter(c,p,p.transformed?'#e8ba65':'#78d4d9',true);c.globalAlpha=1;
  shots.forEach(s=>{c.fillStyle='#f6c09e';c.beginPath();c.ellipse(s.x,s.y,19,10,0,0,TAU);c.fill();c.fillStyle='#ffe8c5';c.beginPath();c.arc(s.x,s.y,6,0,TAU);c.fill();});if(beam>0){c.strokeStyle='#a2e6f3';c.lineWidth=25;c.beginPath();c.moveTo(p.x+beamDir*25,beamY);c.lineTo(beamDir>0?960:0,beamY);c.stroke();c.strokeStyle='#ebfcff';c.lineWidth=8;c.stroke();}fx.forEach(f=>{c.globalAlpha=f.life*2;c.fillStyle=f.color;c.fillRect(f.x,f.y,4,4);});c.globalAlpha=1;
  c.fillStyle='rgba(14,25,48,.9)';c.fillRect(16,16,928,81);text(c,'KAEL • '+(p.transformed?'FORMA AURORA':'GUARDIÃO CELESTE'),30,39,14);bar(c,30,49,290,p.hp/150,'#8ad5bb');bar(c,30,65,290,p.energy/100,'#97d7ed');text(c,`Domínio ${mastery} / 6 • Combo ${comboWindow>0?combo:0}/3`,30,88,12);text(c,rivals[stage].name,925,39,15,'#f1f5ff','right');bar(c,620,49,305,e.hp/e.maxHp,'#e7a6b4');text(c,`Duelo ${stage+1}/3${e.phase===2?' • FÚRIA DO ECLIPSE':''}`,925,82,13,'#e7d6ef','right');
  if(charge>0){bar(c,p.x-35,p.y-91,70,charge/1.6,'#b3edff');text(c,'SOLTE O RAIO',p.x,p.y-98,11,'#d7faff','center');}if(messageTime>0){c.fillStyle='rgba(14,25,48,.88)';c.fillRect(26,477,908,45);text(c,message,480,505,13,'#f3f2df','center');}
  if(state==='down'||state==='between'){c.fillStyle='rgba(13,24,43,.72)';c.fillRect(195,185,570,145);text(c,state==='down'?'A energia se renova.':'Duelo concluído!',480,230,29,'#f5e5c8','center');text(c,state==='down'?'Interaja para tentar novamente':'Interaja para seguir • vida e energia recuperadas',480,277,16,'#d6eafb','center');}c.restore();}
 start();if(stored.completed===true&&stage===2){state='won';e.hp=0;}return{update,draw,getState:()=>({player:{...p},enemy:{...e},stage,mastery,wins,energy:p.energy,transformed:p.transformed,charge,combo,status:state,score}),restart(){stage=0;score=0;start();save();},destroy(){save();}};
}
