export const metadata={id:'ninja',title:'Ninja do Vento',description:'Domine o vento, proteja três santuários e enfrente o guardião da tempestade.',controls:[{action:'jump',label:'Salto duplo / salto na parede'},{action:'attack',label:'Combo'},{action:'special',label:'Shuriken'},{action:'dash',label:'Substituição'},{action:'interact',label:'Clone do vento'}]};
export function createGame(r){
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),safe=(v,d=0)=>Number.isFinite(v)?Math.max(0,Math.min(v,1e8)):d;
 let saved;try{saved=r.save?.load?.()||{};}catch{saved={};}let stage=Math.min(2,Math.floor(safe(saved.stage))),xp=safe(saved.xp),best=safe(saved.best),score=0,status='playing',time=0,hud=0,chakra=100,combo=0,comboClock=0,clone=0,cloneCooldown=0,shots=[],foes=[],fx=[],platforms=[],cleared=false;
 const p={x:100,y:400,w:28,h:44,vx:0,vy:0,hp:6,facing:1,ground:false,jumps:0,inv:0,attack:0,dash:0};
 const names=['Portões de Bambu','Telhados da Chuva','Santuário da Tempestade'];
 const sound=(name,f)=>{if(r.settings?.sound!==false)r.audio?.play?.(name,{frequency:f,duration:.09,volume:.12});};
 const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
 const persist=()=>r.save?.store?.({stage,xp,best:Math.max(best,score),completed:status==='won',version:1});
 function puff(x,y,color){if(r.settings?.reducedMotion)return;for(let i=0;i<10;i++)fx.push({x,y,vx:Math.cos(i*2.4)*90,vy:Math.sin(i*2.4)*90,life:.45,color});}
 function build(){chakra=100;shots=[];fx=[];clone=0;cloneCooldown=0;cleared=false;Object.assign(p,{x:100,y:410,vx:0,vy:0,hp:6,ground:false,jumps:0,inv:1.5,attack:0,dash:0});platforms=[{x:0,y:470,w:960,h:70},{x:170,y:350,w:160,h:18},{x:620,y:350,w:170,h:18}];if(stage>0)platforms.push({x:405,y:255,w:150,h:18});foes=Array.from({length:3+stage},(_,i)=>({x:360+i*110,y:428,w:30,h:42,hp:2+stage,max:2+stage,phase:'approach',clock:i*.3,inv:0,facing:-1,boss:false}));if(stage===2)foes.push({x:800,y:398,w:54,h:72,hp:16,max:16,phase:'approach',clock:1,inv:0,facing:-1,boss:true});r.message?.(`${stage+1}/3 · ${names[stage]} · Derrote os sentinelas e alcance o portão à direita.`);}
 function strike(e,n=1){if(e.hp<=0||e.inv>0)return;e.hp-=n;e.inv=.24;puff(e.x+15,e.y+20,'#9aefdf');sound('hit',420);if(e.hp<=0){score+=e.boss?1200:150;xp+=e.boss?100:20;chakra=clamp(chakra+15,0,100);persist();}}
 function hurt(){if(p.inv>0)return;p.hp--;p.inv=1.1;p.vy=-210;puff(p.x,p.y,'#f9b879');sound('hurt',160);if(p.hp<=0){status='defeated';persist();r.message?.('Missão interrompida · use Reiniciar para tentar novamente.');}}
 function update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(.04,Math.max(0,dt));if(status!=='playing')return;time+=dt;hud-=dt;p.inv-=dt;p.attack-=dt;p.dash-=dt;comboClock-=dt;clone-=dt;cloneCooldown-=dt;chakra=clamp(chakra+9*dt,0,100);const axis=r.input.axis('x');if(axis)p.facing=Math.sign(axis);p.vx=axis*(p.dash>0?680:260);if(p.dash>0)p.vx=p.facing*680;
 if(r.input.pressed('jump')&&(p.jumps<2||p.x<=1||p.x>=930)){const wall=!p.ground&&(p.x<=1||p.x>=930);p.vy=-560;p.jumps=wall?1:p.jumps+1;if(wall){p.facing=p.x<=1?1:-1;p.dash=.15;p.inv=.15;}sound('jump',640);}
 if(!r.input.down('jump')&&p.vy<-230)p.vy+=1050*dt;
 if(r.input.pressed('dash')&&chakra>=20&&p.dash<=0){chakra-=20;p.dash=.22;p.inv=.4;puff(p.x,p.y,'#dee6c7');sound('dash',280);}
 if(r.input.pressed('attack')&&p.attack<=0){combo=comboClock>0?combo%3+1:1;comboClock=.8;p.attack=.27;const box={x:p.facing>0?p.x:p.x-65,y:p.y-8,w:93,h:60};for(const e of foes)if(hit(box,e))strike(e,combo===3?2:1);sound('swing',300+combo*90);}
 if(r.input.pressed('special')&&chakra>=15){chakra-=15;shots.push({x:p.x+14,y:p.y+18,vx:p.facing*570,life:1.7,friendly:true});sound('throw',820);}
 if(r.input.pressed('interact')&&chakra>=50&&cloneCooldown<=0){chakra-=50;clone=5;cloneCooldown=10;r.message?.('Clone do vento · ataques conjuntos por 5 segundos');}
 const oldY=p.y;p.x=clamp(p.x+p.vx*dt,0,932);p.vy=Math.min(850,p.vy+1450*dt);p.y+=p.vy*dt;p.ground=false;for(const q of platforms)if(p.x+p.w>q.x&&p.x<q.x+q.w&&p.vy>=0&&oldY+p.h<=q.y+5&&p.y+p.h>=q.y){p.y=q.y-p.h;p.vy=0;p.ground=true;p.jumps=0;}
 for(const e of foes){if(e.hp<=0)continue;e.inv-=dt;e.clock-=dt;e.facing=p.x<e.x?-1:1;const dist=Math.abs(p.x-e.x);if(e.phase==='approach'){e.x=clamp(e.x+e.facing*(e.boss?58:65+stage*12)*dt,10,890);if(e.clock<=0&&dist<(e.boss?650:300)){e.phase='warning';e.clock=e.boss?.9:.7;}}else if(e.phase==='warning'&&e.clock<=0){e.phase='recover';e.clock=e.boss?1.1:1.4;shots.push({x:e.x+15,y:e.y+19,vx:e.facing*(e.boss?330:240),life:3,friendly:false});if(e.boss)shots.push({x:e.x+15,y:e.y-60,vx:e.facing*270,life:3,friendly:false});}else if(e.phase==='recover'&&e.clock<=0){e.phase='approach';e.clock=.25;}if(hit(p,e)&&p.dash<=0)hurt();if(clone>0&&Math.floor((time-dt)*2)!==Math.floor(time*2)&&dist<180)strike(e);}
 for(const s of shots){s.x+=s.vx*dt;s.life-=dt;const box={x:s.x-7,y:s.y-7,w:14,h:14};if(s.friendly){for(const e of foes)if(e.hp>0&&hit(box,e)){strike(e);s.life=0;break;}}else if(hit(box,p)){hurt();s.life=0;}}shots=shots.filter(s=>s.life>0&&s.x>-20&&s.x<980);for(const f of fx){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}fx=fx.filter(f=>f.life>0);
 if(!cleared&&foes.every(e=>e.hp<=0)){cleared=true;r.message?.('Santuário protegido! Alcance o portão →');}if(cleared&&p.x>885){score+=500;if(stage<2){stage++;persist();build();}else{status='won';persist();r.complete?.({score,stars:p.hp>=4?3:2,xp});}}
 if(hud<=0){hud=.2;r.report?.({title:metadata.title,message:cleared?'Alcance o portão →':names[stage],score,level:stage+1,health:p.hp,energy:Math.round(chakra),coins:xp,status});}}
 function oval(c,x,y,a,b,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,a,b,0,0,7);c.fill();}
 function ninja(c,x,y,facing,color,boss=false,alpha=1){c.save();c.globalAlpha=alpha;c.translate(x,y);c.scale(facing*(boss?1.5:1),boss?1.5:1);oval(c,0,22,20,5,'#0004');const run=Math.sin(time*13)*Math.min(1,Math.abs(p.vx)/260);c.strokeStyle='#14243b';c.lineWidth=8;c.lineCap='round';c.beginPath();c.moveTo(-5,5);c.lineTo(-8+run*5,20);c.moveTo(5,5);c.lineTo(8-run*5,20);c.stroke();c.fillStyle=color;c.fillRect(-12,-13,24,27);oval(c,0,-23,13,14,'#e9bb94');c.fillStyle='#18263d';c.beginPath();c.moveTo(-14,-20);c.lineTo(-17,-40);c.lineTo(-5,-34);c.lineTo(2,-43);c.lineTo(14,-31);c.lineTo(13,-20);c.fill();c.fillStyle='#86d9d6';c.fillRect(-13,-29,26,5);c.fillStyle='#26364a';c.fillRect(-9,-16,20,9);c.fillStyle='#fff0ca';c.fillRect(5,-23,4,3);c.fillStyle=color;c.beginPath();c.moveTo(-10,-13);c.lineTo(-38,-19+Math.sin(time*6)*4);c.lineTo(-25,-7);c.fill();c.restore();}
 function draw(c){c.save();const colors=[['#132d42','#2a6466'],['#24283f','#74647d'],['#16283d','#496077']][stage],g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,colors[0]);g.addColorStop(1,colors[1]);c.fillStyle=g;c.fillRect(0,0,960,540);oval(c,780,90,47,47,'#f3db9b');for(let i=0;i<12;i++){let x=i*95;c.fillStyle='#101e3244';c.fillRect(x,200+i%3*35,65,300);c.beginPath();c.moveTo(x-20,220+i%3*35);c.lineTo(x+32,175+i%3*35);c.lineTo(x+84,220+i%3*35);c.fill();}for(let i=0;i<9;i++){c.strokeStyle='#73bca233';c.lineWidth=7;c.beginPath();c.moveTo(i*120+20,470);c.lineTo(i*120+30,110);c.stroke();for(let j=0;j<4;j++)oval(c,i*120+45,160+j*60,25,6,'#82b6a333');}for(const q of platforms){c.fillStyle='#253849';c.fillRect(q.x,q.y,q.w,q.h);c.fillStyle='#7fa6a2';c.fillRect(q.x,q.y,q.w,5);c.fillStyle='#bdc3a2';for(let x=q.x;x<q.x+q.w;x+=28)c.fillRect(x,q.y+6,22,3);}c.fillStyle=cleared?'#bff2bb':'#506981';c.fillRect(910,355,10,115);c.fillRect(870,355,10,115);c.fillRect(860,350,72,10);for(const e of foes){if(e.hp<=0)continue;ninja(c,e.x+e.w/2,e.y+e.h-23,e.facing,e.boss?'#b5839d':'#ab8368',e.boss);c.fillStyle='#182739';c.fillRect(e.x-3,e.y-30,e.w+6,5);c.fillStyle='#efb99e';c.fillRect(e.x-3,e.y-30,(e.w+6)*Math.max(0,e.hp/e.max),5);if(e.phase==='warning'){c.fillStyle='#ffe19b';c.font='bold 25px system-ui';c.fillText('!',e.x+10,e.y-40);c.strokeStyle='#ffe19b88';c.setLineDash([7,9]);c.beginPath();c.moveTo(e.x,e.y+19);c.lineTo(e.x+e.facing*280,e.y+19);c.stroke();c.setLineDash([]);}}
 if(clone>0)ninja(c,p.x-32*p.facing,p.y+22,p.facing,'#98ddc1',false,.4);ninja(c,p.x+14,p.y+22,p.facing,'#77baa9',false,p.inv>0?.7:1);if(p.attack>0){c.strokeStyle=combo===3?'#fff0a9':'#bdf4e2';c.lineWidth=5;c.beginPath();c.arc(p.x+14,p.y+20,52,p.facing>0?-1.1:2,p.facing>0?1.1:4.2);c.stroke();}for(const s of shots){c.save();c.translate(s.x,s.y);c.rotate(time*15);c.fillStyle=s.friendly?'#c1fff0':'#f4b190';c.beginPath();for(let i=0;i<8;i++){let a=i*Math.PI/4,rad=i%2?3:11;c.lineTo(Math.cos(a)*rad,Math.sin(a)*rad);}c.closePath();c.fill();c.restore();}for(const f of fx){c.globalAlpha=f.life*2;c.fillStyle=f.color;c.fillRect(f.x,f.y,4,4);}c.globalAlpha=1;c.fillStyle='#122339de';c.fillRect(18,18,390,82);c.fillStyle='#e9ead2';c.font='bold 18px system-ui';c.fillText(`${stage+1}/3 · ${names[stage]}`,32,43);c.font='13px system-ui';c.fillText(`${'♥'.repeat(Math.max(0,p.hp))}   CHAKRA ${Math.floor(chakra)}   MAESTRIA ${Math.floor(xp/100)+1}`,32,66);c.fillStyle='#426572';c.fillRect(32,80,350,5);c.fillStyle='#9ae6cd';c.fillRect(32,80,350*chakra/100,5);if(status==='defeated'){c.fillStyle='#101d35db';c.fillRect(0,0,960,540);c.fillStyle='#ffe0bb';c.font='bold 34px system-ui';c.textAlign='center';c.fillText('O vento pede uma nova tentativa',480,245);c.font='18px system-ui';c.fillText('Reiniciar retoma esta missão · maestria preservada',480,290);}c.restore();}
 function restart(){if(status==='won'){stage=0;score=0;}status='playing';build();persist();}
 build();if(saved.completed===true)status='won';return{update,draw,restart,destroy:persist,getState:()=>({status,stage:stage+1,level:stage+1,quest:names[stage],score,xp,mastery:Math.floor(xp/100)+1,chakra,energy:chakra,clone,cloneCooldown,cleared,player:{...p},enemies:foes.map(e=>({...e})),platforms:platforms.map(q=>({...q})),shots:shots.map(s=>({...s}))})};
}
