import 'dotenv/config';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import cookie from '@fastify/cookie';
import jwt from '@fastify/jwt';
import argon2 from 'argon2';
import pg from 'pg';
import { z } from 'zod';
import nodemailer from 'nodemailer';
import crypto from 'node:crypto';

const { Pool } = pg;
const app = Fastify({ logger: true, bodyLimit: 32 * 1024 });
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const required = ['DATABASE_URL','JWT_SECRET','DEVICE_INGEST_SECRET'];
for (const k of required) if (!process.env[k]) app.log.warn(`${k} is not configured; related routes won't work securely`);
await app.register(helmet, { contentSecurityPolicy: false });
await app.register(cors, { origin: (process.env.FRONTEND_ORIGIN || 'http://localhost:5500').split(','), credentials: true });
await app.register(rateLimit, { max: 100, timeWindow: '1 minute' });
await app.register(cookie);
if (process.env.JWT_SECRET) await app.register(jwt, { secret: process.env.JWT_SECRET, sign: { expiresIn: '20m' }, cookie: { cookieName: 'nb_session', signed: false } });
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}) : null;
const emailSchema=z.string().email().max(254);const passwordSchema=z.string().min(12).max(128);const nameSchema=z.string().trim().min(2).max(80);
function hashToken(s){return crypto.createHash('sha256').update(s).digest('hex')}
async function auth(req,reply){try{await req.jwtVerify();return true}catch{reply.code(401).send({error:'Sessão inválida ou expirada'});return false}}
async function guardian(req,reply){if(!await auth(req,reply))return false;if(!req.user||req.user.role!=='guardian'){reply.code(403).send({error:'Acesso restrito ao responsável'});return false}return true}
async function childAuth(req,reply){try{await req.jwtVerify({onlyCookie:'nb_kid_session'});return true}catch{reply.code(401).send({error:'Sessão infantil inválida ou expirada'});return false}}
async function ownedChild(guardianId,childId){const r=await pool.query('SELECT id,display_name FROM children WHERE id=$1 AND guardian_id=$2',[childId,guardianId]);return r.rows[0]}
app.get('/api/health',async()=>{let database='unconfigured';if(process.env.DATABASE_URL){try{await pool.query('SELECT 1');database='connected'}catch{database='unavailable'}}return {ok:true,service:'NeuroBloom API',time:new Date().toISOString(),database};});
app.post('/api/auth/signup',async(req,reply)=>{const schema=z.object({guardianName:nameSchema, email:emailSchema, password:passwordSchema, childName:nameSchema, birthYear:z.number().int().min(1900).max(new Date().getFullYear()).optional(), kidPin:z.string().min(6).max(32), consent:z.literal(true)});const v=schema.safeParse(req.body);if(!v.success)return reply.code(400).send({error:'Dados inválidos',details:v.error.flatten()});try{const p=v.data;const ph=await argon2.hash(p.password);const kh=await argon2.hash(p.kidPin);const client=await pool.connect();let g,c;try{await client.query('BEGIN');g=(await client.query('INSERT INTO guardians(name,email,password_hash,consent_at) VALUES($1,$2,$3,now()) RETURNING id,name,email',[p.guardianName,p.email.toLowerCase(),ph])).rows[0];c=(await client.query('INSERT INTO children(guardian_id,display_name,birth_year,kid_pin_hash) VALUES($1,$2,$3,$4) RETURNING id,display_name',[g.id,p.childName,p.birthYear||null,kh])).rows[0];await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}const token=app.jwt.sign({sub:g.id,role:'guardian'});reply.setCookie('nb_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:1200});return reply.code(201).send({guardian:g,child:{id:c.id,name:c.display_name,kidUrl:`${process.env.FRONTEND_ORIGIN||'http://localhost:5500'}/#child=${c.id}`},message:'Conta criada. Configure assinatura e confirme o e-mail para produção.'})}catch(e){req.log.error(e);if(e.code==='23505')return reply.code(409).send({error:'E-mail já cadastrado'});return reply.code(500).send({error:'Não foi possível criar a conta'})}});
app.post('/api/auth/login',async(req,reply)=>{const v=z.object({email:emailSchema,password:z.string().min(1).max(128)}).safeParse(req.body);if(!v.success)return reply.code(400).send({error:'Dados inválidos'});const r=await pool.query('SELECT id,name,email,password_hash FROM guardians WHERE email=$1',[v.data.email.toLowerCase()]);if(!r.rowCount||!(await argon2.verify(r.rows[0].password_hash,v.data.password)))return reply.code(401).send({error:'E-mail ou senha inválidos'});const g=r.rows[0],token=app.jwt.sign({sub:g.id,role:'guardian'});reply.setCookie('nb_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:1200});return {guardian:{id:g.id,name:g.name,email:g.email}}});
app.post('/api/auth/logout',async(_,reply)=>reply.clearCookie('nb_session',{path:'/'}).send({ok:true}));
app.get('/api/family', {preHandler:guardian},async req=>{const g=await pool.query('SELECT id,name,email,created_at FROM guardians WHERE id=$1',[req.user.sub]);const c=await pool.query('SELECT id,display_name,birth_year,created_at FROM children WHERE guardian_id=$1',[req.user.sub]);const s=await pool.query('SELECT status,amount_cents,created_at FROM subscriptions WHERE guardian_id=$1 ORDER BY created_at DESC LIMIT 1',[req.user.sub]);return {guardian:g.rows[0],children:c.rows,subscription:s.rows[0]||{status:'inactive',amount_cents:3999}}});
app.post('/api/children/:id/kid-login',async(req,reply)=>{const v=z.object({pin:z.string().min(1).max(32)}).safeParse(req.body);if(!v.success)return reply.code(400).send({error:'PIN inválido'});const r=await pool.query('SELECT id,guardian_id,display_name,kid_pin_hash FROM children WHERE id=$1',[req.params.id]);if(!r.rowCount||!(await argon2.verify(r.rows[0].kid_pin_hash,v.data.pin)))return reply.code(401).send({error:'Código infantil inválido'});const c=r.rows[0],token=app.jwt.sign({sub:c.id,guardianId:c.guardian_id,role:'child'},{expiresIn:'30m'});reply.setCookie('nb_kid_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:1800});return {child:{id:c.id,name:c.display_name},message:'Sessão infantil iniciada'}});
app.get('/api/children/me',{preHandler:childAuth},async req=>{const r=await pool.query('SELECT id,display_name FROM children WHERE id=$1 AND guardian_id=$2',[req.user.sub,req.user.guardianId]);if(!r.rowCount)return {child:null};return {child:{id:r.rows[0].id,name:r.rows[0].display_name}}});
app.post('/api/children/logout',async(_,reply)=>reply.clearCookie('nb_kid_session',{path:'/'}).send({ok:true}));
app.get('/api/children/:id/vitals/latest',{preHandler:guardian},async(req,reply)=>{if(!await ownedChild(req.user.sub,req.params.id))return reply.code(404).send({error:'Perfil não encontrado'});const r=await pool.query('SELECT bpm,signal_quality,measured_at,received_at FROM vitals WHERE child_id=$1 ORDER BY measured_at DESC LIMIT 1',[req.params.id]);return {reading:r.rows[0]||null,notice:'Leitura de sensor não é diagnóstico nem substitui orientação médica.'}});
app.get('/api/children/:id/vitals',{preHandler:guardian},async(req,reply)=>{if(!await ownedChild(req.user.sub,req.params.id))return reply.code(404).send({error:'Perfil não encontrado'});const lim=Math.min(Number(req.query.limit)||100,500);const r=await pool.query('SELECT bpm,signal_quality,measured_at FROM vitals WHERE child_id=$1 ORDER BY measured_at DESC LIMIT $2',[req.params.id,lim]);return {readings:r.rows}});
app.post('/api/children/:id/vitals/ble',{preHandler:guardian},async(req,reply)=>{if(!await ownedChild(req.user.sub,req.params.id))return reply.code(404).send({error:'Perfil não encontrado'});const v=z.object({bpm:z.number().int().min(25).max(250),signalQuality:z.number().int().min(0).max(100),measuredAt:z.string().datetime()}).safeParse(req.body);if(!v.success)return reply.code(400).send({error:'Leitura BLE inválida'});await pool.query('INSERT INTO vitals(child_id,bpm,signal_quality,measured_at) VALUES($1,$2,$3,$4)',[req.params.id,v.data.bpm,v.data.signalQuality,v.data.measuredAt]);return reply.code(202).send({accepted:true})});
app.post('/api/device/reading',async(req,reply)=>{const secret=String(req.headers['x-device-secret']||'');const v=z.object({deviceId:z.string().uuid(),bpm:z.number().int().min(25).max(250),signalQuality:z.number().int().min(0).max(100),measuredAt:z.string().datetime()}).safeParse(req.body);if(!v.success)return reply.code(400).send({error:'Leitura inválida',details:v.error.flatten()});if(secret.length<32)return reply.code(401).send({error:'Dispositivo não autenticado'});const d=await pool.query('SELECT child_id,device_key_hash FROM devices WHERE id=$1',[v.data.deviceId]);if(!d.rowCount||!crypto.timingSafeEqual(Buffer.from(hashToken(secret),'hex'),Buffer.from(d.rows[0].device_key_hash,'hex')))return reply.code(401).send({error:'Dispositivo não autenticado'});await pool.query('INSERT INTO vitals(child_id,bpm,signal_quality,measured_at) VALUES($1,$2,$3,$4)',[d.rows[0].child_id,v.data.bpm,v.data.signalQuality,v.data.measuredAt]);await pool.query('UPDATE devices SET last_seen=now() WHERE id=$1',[v.data.deviceId]);return reply.code(202).send({accepted:true})});
app.post('/api/children/:id/device-enrollment', {preHandler:guardian},async(req,reply)=>{if(!await ownedChild(req.user.sub,req.params.id))return reply.code(404).send({error:'Perfil não encontrado'});const key=crypto.randomBytes(32).toString('hex');const r=await pool.query('INSERT INTO devices(child_id,device_key_hash) VALUES($1,$2) RETURNING id,label',[req.params.id,hashToken(key)]);return reply.code(201).send({device:r.rows[0],deviceSecret:key,warning:'Copie agora; segredo exibido uma única vez. Para produção, implemente rotação e autenticação por dispositivo.'})});
app.post('/api/alerts/test-email',{preHandler:guardian},async(req,reply)=>{if(!mailer)return reply.code(503).send({error:'SMTP ainda não configurado no servidor'});const r=await pool.query('SELECT email,name FROM guardians WHERE id=$1',[req.user.sub]);await mailer.sendMail({from:process.env.MAIL_FROM,to:r.rows[0].email,subject:'NeuroBloom — teste de notificação',text:`Olá ${r.rows[0].name}, este é um e-mail de teste do NeuroBloom. Não é um alerta médico nem indica leitura real.`});return {sent:true}});
app.post('/api/billing/checkout', {preHandler:guardian},async(_,reply)=>reply.code(501).send({error:'Checkout PagBank ainda não conectado. Não envie cobrança: configurar credenciais e fluxo oficial do provedor é necessário.'}));
app.post('/api/webhooks/pagbank',async(req,reply)=>{req.log.warn('Webhook PagBank recebido mas validação de assinatura ainda não implementada; ignorado.');return reply.code(501).send({error:'Webhook não habilitado até validação criptográfica e idempotência'})});
app.setErrorHandler((err,req,reply)=>{req.log.error(err);reply.code(500).send({error:'Erro interno'})});
const port=Number(process.env.PORT||3333);try{await app.listen({port,host:process.env.HOST||'127.0.0.1'})}catch(e){app.log.error(e);process.exit(1)}
